Result
matrixorigin/matrixorigin.io.cn pull request #1013
Opened 2024-04-08 03:44 UTC by yangj1211

## What type of PR is this?

- [ ] Enhancement
- [ ] Displaying
- [ ] Typo
- [x] Doc Request

## Which issue(s) this PR fixes:

issue #1012

## What this PR does / why we need it:

2024-04-24 09:44 UTC, yangj1211 commented
1.2 feature

2024-04-30 01:56 UTC, dengn requested changes

2024-04-30 01:56 UTC, dengn commented on docs/MatrixOne/Reference/Variable/system-variables/keep_user_target_list_in_result.md
> +set global keep_user_target_list_in_result = 1;// 默认为 0，重新连接数据库生效
现在默认应该是1，需要确认下

2024-04-30 02:42 UTC, yangj1211 commented
现在默认值还是0，没有改动，与研发确认表示改动为1要改很多bvt。
 
<img width="469" alt="image" src="https://github.com/matrixorigin/matrixorigin.io.cn/assets/153493538/e21936c2-852a-44f3-ae71-6a266a5231e6">

2024-05-20 02:48 UTC, closed without merging