modify version number 0.5.1 to 0.6.0
matrixorigin/matrixorigin.io.cn pull request #121
Opened 2022-11-30 06:05 UTC by lacrimosaprinz

2022-11-30 14:15 UTC, dengn requested changes

2022-11-30 14:15 UTC, dengn commented on docs/MatrixOne/Develop/export-data/export-data.md
> +docker run -d -p 6001:6001 -v ~/tmp/docker_export_demo/store:/store:rw --name matrixone matrixorigin/matrixone:0.6.0
docker启动不光是改个版本号

2022-12-01 03:14 UTC, lacrimosaprinz commented on docs/MatrixOne/Develop/export-data/export-data.md
> +docker run -d -p 6001:6001 -v ~/tmp/docker_export_demo/store:/store:rw --name matrixone matrixorigin/matrixone:0.6.0
这个文档从navigation里拿掉了， 我去修改【Export data by SELECT INTO...OUTFILE】这篇吧，docker先能挂载配置文件，挂载数据目录这一块我去跟进一下王垒

2022-12-06 10:01 UTC, dengn approved these changes

2022-12-07 10:15 UTC, closed without merging