add system variable docs
matrixorigin/matrixorigin.io.cn pull request #290
Opened 2023-03-21 09:14 UTC by lacrimosaprinz

## What type of PR is this?

- [ ] Enhancement
- [ ] Displaying
- [ ] Typo
- [x] Doc Request

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

2023-03-21 09:16 UTC, YANGGMM approved these changes

2023-03-31 03:36 UTC, dengn requested changes

2023-03-31 03:36 UTC, dengn commented on docs/MatrixOne/Reference/Variable/system-variables/system-variables-overview.md
> +- **全局变量**：是指对所有连接的 MatrixOne Server 实例都适用的变量。它们的值在 MatrixOne Server 启动时设置，并在 MatrixOne Server 关闭之前保持不变。全局变量通常用于控制 MatrixOne Server 的行为，例如指定默认备份和恢复位置，指定默认语言环境等。
这个理解有点错误：”全局“是指连接MatrixOne Server的所有会话Session，“会话”是指当前连接MatrixOne Server的会话Session。

2023-03-31 03:36 UTC, dengn commented on docs/MatrixOne/Reference/Variable/system-variables/sql-mode.md
> +- ALLOW_INVALID_DATES：ALLOW_INVALID_DATES 在 MatrixOne SQL 模式中被称为**宽松模式（loose mode）**。在 ALLOW_INVALID_DATES 模式下，MatrixOne 允许插入一些在标准日期格式中是无效的日期，如 '0000-00-00' 或 '2000-00-00'。此模式是为了兼容一些早期版本的 MySQL 和非标准的
这个试验了看起来跑不了啊
mysql> set sql_mode = 'ALLOW_INVALID_DATES';
Query OK, 0 rows affected (0.01 sec)

mysql> select @@sql_mode;
+---------------------+
| @@sql_mode          |
+---------------------+
| ALLOW_INVALID_DATES |
+---------------------+
1 row in set (0.00 sec)

mysql> create table a(b date);
Query OK, 0 rows affected (0.30 sec)

mysql> insert into a values("2023-00-00");
ERROR 20203 (HY000): invalid argument parsedate, bad value 2023-00-00

2023-03-31 06:43 UTC, lacrimosaprinz commented on docs/MatrixOne/Reference/Variable/system-variables/sql-mode.md
> +- ALLOW_INVALID_DATES：ALLOW_INVALID_DATES 在 MatrixOne SQL 模式中被称为**宽松模式（loose mode）**。在 ALLOW_INVALID_DATES 模式下，MatrixOne 允许插入一些在标准日期格式中是无效的日期，如 '0000-00-00' 或 '2000-00-00'。此模式是为了兼容一些早期版本的 MySQL 和非标准的
@YANGGMM 看看这个模式是不是不支持

2023-04-06 07:48 UTC, merged