add new doc of lower case table names system variable
matrixorigin/matrixorigin.io.cn pull request #296
Opened 2023-03-23 06:39 UTC by lacrimosaprinz

## What type of PR is this?

- [ ] Enhancement
- [ ] Displaying
- [ ] Typo
- [x] Doc Request

## Which issue(s) this PR fixes:

issue #
https://github.com/matrixorigin/matrixone/issues/7488
## What this PR does / why we need it:

2023-03-23 06:40 UTC, iamlinjunhong approved these changes

2023-03-28 06:15 UTC, dengn requested changes
最好增加一个这5种模式与mysql兼容性的对比

2023-03-28 06:51 UTC, lacrimosaprinz commented
这个与mysql兼容性我也可以同时增加到系统变量总表里，这篇文档里提一下参数 0,1 兼容mysql

2023-03-31 04:28 UTC, dengn approved these changes

2023-03-31 04:44 UTC, merged