add sequence doc for 0.8
matrixorigin/matrixorigin.io.cn pull request #297
Opened 2023-03-24 06:59 UTC by lacrimosaprinz

## What type of PR is this?

- [ ] Enhancement
- [ ] Displaying
- [ ] Typo
- [x] Doc Request

## Which issue(s) this PR fixes:

issue #
https://github.com/matrixorigin/matrixone/issues/6590
## What this PR does / why we need it:

2023-03-27 02:48 UTC, iceTTTT approved these changes

2023-03-31 04:11 UTC, dengn requested changes

2023-03-31 04:11 UTC, dengn commented on docs/MatrixOne/Reference/SQL-Reference/Data-Definition-Language/0.8-create-sequence.md
> +#### `LASTVAL()`
这个里面没有说明sequence是怎么在table里使用的。只说了这个sequence本身，sequence肯定不是一个独立存在的东西。

2023-03-31 04:11 UTC, dengn commented on docs/MatrixOne/Reference/SQL-Reference/Data-Definition-Language/0.8-create-sequence.md
> +#### `LASTVAL()`
是否类似这里的example3， https://www.geeksforgeeks.org/postgresql-create-sequence/

2023-04-10 08:28 UTC, dengn approved these changes

2023-04-10 08:37 UTC, dengn requested changes
加个说明：auto_increment与sequence不能一起用，一起用的话会报错。
mysql> create table abc(a int auto_increment default nextval('seq_id'), b int);      
ERROR 20301 (HY000): invalid input: invalid default value for 'a'

2023-04-10 09:16 UTC, domingozhang approved these changes

2023-04-13 07:43 UTC, dengn approved these changes

2023-04-13 07:43 UTC, merged