add the doc of insert on duplicate key
matrixorigin/matrixorigin.io.cn pull request #301
Opened 2023-03-27 08:42 UTC by lacrimosaprinz

## What type of PR is this?

- [ ] Enhancement
- [ ] Displaying
- [ ] Typo
- [x] Doc Request

## Which issue(s) this PR fixes:

issue #
https://github.com/matrixorigin/matrixone/issues/6567
## What this PR does / why we need it:

2023-04-11 09:22 UTC, ouyuanning approved these changes

2023-04-13 07:44 UTC, dengn requested changes

2023-04-13 07:44 UTC, dengn commented on docs/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Language/0.8-insert-on-duplicate.md
> +需要注意的是，使用该语法的前提是需要在表中建立主键约束，以便判断是否有重复记录。同时，更新操作和插入操作都需要设置对应的列值，否则会导致语法错误。
说明下还不支持唯一键

2023-04-13 08:02 UTC, dengn approved these changes

2023-04-13 08:02 UTC, merged