add the docs of pub-sub sql statments
matrixorigin/matrixorigin.io.cn pull request #329
Opened 2023-05-05 10:07 UTC by lacrimosaprinz

## What type of PR is this?

- [ ] Enhancement
- [ ] Displaying
- [ ] Typo
- [x] Doc Request

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

2023-05-10 02:29 UTC, domingozhang approved these changes

2023-05-14 01:35 UTC, dengn requested changes

2023-05-14 01:35 UTC, dengn commented on docs/MatrixOne/Reference/SQL-Reference/Other/SHOW-Statements/show-subscriptions.md
> +reate database sub1 from sys publication pub1;
Create

2023-05-16 09:56 UTC, dengn approved these changes

2023-05-16 09:56 UTC, merged