add doc of key feature htap
matrixorigin/matrixorigin.io.cn pull request #337
Opened 2023-05-10 08:06 UTC by lacrimosaprinz

## What type of PR is this?

- [ ] Enhancement
- [ ] Displaying
- [ ] Typo
- [x] Doc Request

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

2023-05-14 02:12 UTC, dengn requested changes

2023-05-14 02:12 UTC, dengn commented on docs/MatrixOne/Overview/key-feature-htap.md
> +- **一站式体验**：满足单一数据库内事务处理（TP）和分析处理（AP）的所有需求，用户可以获得覆盖整个 TP 和 AP 场景的一站式体验。
这里就是指HTAP，先暂时不要在这里提流吧

2023-05-17 08:20 UTC, domingozhang approved these changes

2023-05-17 08:21 UTC, dengn approved these changes

2023-05-17 08:21 UTC, merged