add docs of migration
matrixorigin/matrixorigin.io.cn pull request #340
Opened 2023-05-22 05:44 UTC by lacrimosaprinz

## What type of PR is this?

- [ ] Enhancement
- [ ] Displaying
- [ ] Typo
- [x] Doc Request

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

2023-05-30 08:59 UTC, domingozhang approved these changes

2023-05-30 09:06 UTC, dengn requested changes

2023-05-30 09:06 UTC, dengn commented on docs/MatrixOne/Migrate/migrate-overview.md
> +### CN 直接写 S3
这个CN写S3 跟迁移一点关系都没有，这只是MO自己写数据的一种技术方式，并不是个工具，用户又不会操作这个。没必要写这段

MO现在唯一的两种批量导入工具就是load data和source

2023-05-31 06:09 UTC, dengn approved these changes

2023-05-31 06:10 UTC, dengn commented
fix conflict

2023-06-02 06:56 UTC, lacrimosaprinz commented
done

2023-06-02 08:38 UTC, merged