only support locale parameter en_US
matrixorigin/matrixorigin.io.cn pull request #378
Opened 2023-06-16 04:09 UTC by lacrimosaprinz

## What type of PR is this?

- [x] Enhancement
- [ ] Displaying
- [ ] Typo
- [ ] Doc Request

## Which issue(s) this PR fixes:

issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/363
## What this PR does / why we need it:

2023-06-20 02:25 UTC, dengn requested changes

2023-06-20 02:25 UTC, dengn commented on docs/MatrixOne/Reference/Functions-and-Operators/String/format.md
> +`FORMAT(X,D[,locale])` 的参数 `[,locale]` 当前仅支持语言环境参数 `en_US`，其他语言环境参数暂不支持。
这个结论哪来的。测试结论是支持其他的地区的，比如下面这个，就有明显的区别。

```
mysql> SELECT FORMAT(12332.2,2,'de_DE');
+---------------------------+
| format(12332.2, 2, de_DE) |
+---------------------------+
| 12.332,20                 |
+---------------------------+
1 row in set (0.04 sec)

mysql> SELECT FORMAT(12332.2,2,'en_US');
+---------------------------+
| format(12332.2, 2, en_US) |
+---------------------------+
| 12,332.20                 |
+---------------------------+
1 row in set (0.07 sec)
```

2023-06-20 06:18 UTC, lacrimosaprinz commented on docs/MatrixOne/Reference/Functions-and-Operators/String/format.md
> +`FORMAT(X,D[,locale])` 的参数 `[,locale]` 当前仅支持语言环境参数 `en_US`，其他语言环境参数暂不支持。
@domingozhang  潇哥再帮忙确认一下~

2023-06-27 01:40 UTC, dengn approved these changes

2023-06-27 01:40 UTC, merged