add new doc of purge_log
matrixorigin/matrixorigin.io.cn pull request #458
Opened 2023-07-06 07:50 UTC by lacrimosaprinz

## What type of PR is this?

- [ ] Enhancement
- [ ] Displaying
- [ ] Typo
- [x] Doc Request

## Which issue(s) this PR fixes:

issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/401
## What this PR does / why we need it:

2023-07-07 08:18 UTC, xzxiong approved these changes
LGTM

2023-07-07 08:57 UTC, dengn requested changes

2023-07-07 08:57 UTC, dengn commented on docs/MatrixOne/Reference/Functions-and-Operators/system-ops/purge_log.md
> +`PURGE_LOG()` 用于删除日志。
用于删除记录于MatrixOne数据库系统表中的日志。

2023-07-07 08:57 UTC, dengn commented on docs/MatrixOne/Reference/Functions-and-Operators/system-ops/purge_log.md
> +> PURGE_LOG('sys_table_name', 'date')
输出结果会有什么值？0代表成功？怎么样算失败？

2023-07-10 01:34 UTC, dengn requested changes

2023-07-10 01:34 UTC, dengn commented on docs/MatrixOne/Reference/Functions-and-Operators/system-ops/purge_log.md
> +```
增加一个说明，说我们现在总共就这三张系统日志表，然后加一个link到系统表章节。

2023-07-10 05:50 UTC, dengn approved these changes

2023-07-10 05:51 UTC, merged