add new docs of update data and delete data
matrixorigin/matrixorigin.io.cn pull request #558
Opened 2023-07-14 07:24 UTC by lacrimosaprinz

## What type of PR is this?

- [ ] Enhancement
- [ ] Displaying
- [ ] Typo
- [x] Doc Request

## Which issue(s) this PR fixes:

issue #
https://github.com/matrixorigin/matrixorigin.io.cn/issues/450
https://github.com/matrixorigin/matrixorigin.io.cn/issues/449
## What this PR does / why we need it:

2023-07-14 10:09 UTC, dengn commented
fix conflict

2023-07-14 10:11 UTC, dengn requested changes

2023-07-14 10:11 UTC, dengn commented on docs/MatrixOne/Develop/import-data/delete-data.md
> +
要补充一下这三种删除从SQL语句上删除到真正实际删除释放空间需要多久？我们的GC（garbage collection）机制需要与存储确认一下。

2023-07-17 09:06 UTC, domingozhang approved these changes

2023-07-19 13:07 UTC, dengn approved these changes

2023-07-19 13:14 UTC, dengn commented
Fix conflict

2023-07-20 08:48 UTC, merged