add content of show processlist
matrixorigin/matrixorigin.io.cn pull request #621
Opened 2023-07-25 09:28 UTC by lacrimosaprinz

## What type of PR is this?

- [] Enhancement
- [ ] Displaying
- [ ] Typo
- [x] Doc Request

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

2023-07-28 08:34 UTC, domingozhang approved these changes

2023-07-29 02:58 UTC, dengn requested changes

2023-07-29 02:58 UTC, dengn commented on docs/MatrixOne/Overview/feature/mysql-compatibility.md
> +* 由于架构上的不同，MatrixOne 实现了部分 SHOW 命令仅出于语法的兼容性，这些命令不会产生任何输出，如 `SHOW STATUS/PRIVILEGES` 等。
SHOW PROCESSLIST 有输出内容但是与MySQL差异很大，要在下面那条加上。

2023-07-29 03:01 UTC, dengn requested changes

2023-07-29 03:01 UTC, dengn commented on docs/MatrixOne/Reference/SQL-Reference/Other/SHOW-Statements/show-processlist.md
> +
分布式版本和单机版本会有啥区别，这个问题没有回答

2023-07-29 05:15 UTC, lacrimosaprinz commented on docs/MatrixOne/Reference/SQL-Reference/Other/SHOW-Statements/show-processlist.md
> +
已与潇哥 @domingozhang  确认，分布式与单机版没有区别

2023-08-01 02:03 UTC, dengn approved these changes

2023-08-01 02:03 UTC, merged