new docs of replace
matrixorigin/matrixorigin.io.cn pull request #643
Opened 2023-08-04 11:02 UTC by lacrimosaprinz

## What type of PR is this?

- [ ] Enhancement
- [ ] Displaying
- [ ] Typo
- [x] Doc Request

## Which issue(s) this PR fixes:

issue #
https://github.com/matrixorigin/matrixone/issues/6572
## What this PR does / why we need it:

2023-08-09 07:05 UTC, domingozhang approved these changes

2023-08-09 08:23 UTC, w-zr approved these changes

2023-08-10 03:21 UTC, dengn requested changes

2023-08-10 03:21 UTC, dengn commented on mkdocs.yml
> +          - REPLACE: MatrixOne/Reference/SQL-Reference/Data-Manipulation-Language/replace.md
这是dml的重要语句，应该要放到这些函数的前面去

2023-08-16 01:00 UTC, dengn approved these changes

2023-08-16 01:01 UTC, merged