doc of enum
matrixorigin/matrixorigin.io.cn pull request #646
Opened 2023-08-07 08:08 UTC by lacrimosaprinz

## What type of PR is this?

- [ ] Enhancement
- [ ] Displaying
- [ ] Typo
- [ ] Doc Request

## Which issue(s) this PR fixes:

issue #
https://github.com/matrixorigin/matrixone/issues/6613
## What this PR does / why we need it:

2023-08-07 08:13 UTC, YANGGMM approved these changes

2023-08-07 08:27 UTC, domingozhang approved these changes

2023-08-10 03:23 UTC, dengn reviewed
与MySQL的enum使用有无差异？

2023-08-16 01:05 UTC, dengn requested changes

2023-08-16 01:05 UTC, dengn commented on docs/MatrixOne/Reference/Data-Types/enum-type.md
> +    以下章节**过滤 ENUM 值**和**排序 ENUM 值**是 MySQL 的 ENUM 特性，MatrixOne 暂不支持。
这里跟后面的内容前后矛盾了，过滤 ENUM 值和排序 ENUM 值不支持的话就不用详细介绍，而是直接写到限制里。

2023-08-17 13:07 UTC, dengn approved these changes

2023-08-17 13:08 UTC, merged