modify the content of scaling down
matrixorigin/matrixorigin.io.cn pull request #649
Opened 2023-08-10 08:37 UTC by lacrimosaprinz

## What type of PR is this?

- [ ] Enhancement
- [ ] Displaying
- [ ] Typo
- [x] Doc Request

## Which issue(s) this PR fixes:

issue #
https://github.com/matrixorigin/MO-Cloud/issues/971
## What this PR does / why we need it:

2023-08-11 02:24 UTC, domingozhang approved these changes

2023-08-16 01:11 UTC, dengn requested changes

2023-08-16 01:11 UTC, dengn commented on docs/MatrixOne/Deploy/mgmt-cn-group-using-proxy.md
> +Proxy 在 CN 缩容时如何处理会话的迁移和关闭，以确保负载和租户之间的隔离以及业务的连续性。
这个句子有点奇怪，是个疑问句？

2023-08-17 13:25 UTC, dengn approved these changes

2023-08-17 13:27 UTC, merged