The high cost-effectiveness of columnar storage.
matrixorigin/matrixorigin.io.cn pull request #715
Opened 2023-08-28 09:27 UTC by cyann7

## What type of PR is this?

- [x] Enhancement
- [ ] Displaying
- [ ] Typo
- [ ] Doc Request

## Which issue(s) this PR fixes:

issue #675

## What this PR does / why we need it:
向用户说明我们的优势：列存带来的更高的数据压缩比以降低存储成本。

2023-08-28 09:29 UTC, cyann7 commented
![image](https://github.com/matrixorigin/matrixorigin.io.cn/assets/47444607/38c17df5-9154-4d04-9c70-ea867e6a9103)

2023-08-29 07:31 UTC, dengn requested changes

2023-08-29 07:31 UTC, dengn commented on docs/MatrixOne/Overview/feature/cost-effective.md
> +MatrixOne 总体的数据压缩率最低可达 10%，具体压缩率受实际数据的数据结构、数据冗余程度等多因素影响。
最低可以达到 1%

2023-08-30 13:58 UTC, dengn approved these changes

2023-08-30 13:58 UTC, merged