Update deploy-MatrixOne-cluster.md
matrixorigin/matrixorigin.io.cn pull request #790
Opened 2023-10-19 07:37 UTC by yanghaitao5000

Updated operator installation method

## What type of PR is this?

- [ ] Enhancement
- [ ] Displaying
- [ ] Typo
- [ ] Doc Request

## Which issue(s) this PR fixes:
https://github.com/matrixorigin/matrixorigin.io.cn/issues/717
https://github.com/matrixorigin/matrixorigin.io.cn/issues/747

issue #

## What this PR does / why we need it:
Updated operator deployment method

2023-10-20 00:41 UTC, dengn commented
please run the following to get lint passed:

安装依赖：npm ci
校验：npm run lint
校验并自动修复：npm run lint:fix

2023-10-22 08:52 UTC, dengn requested changes

2023-10-22 08:52 UTC, dengn commented on scripts/mdast-words-count/mdast-words-count
please remove these scripts files, they are unrelated.

2023-10-23 04:06 UTC, yanghaitao5000 commented
该问题已在: https://github.com/matrixorigin/matrixorigin.io.cn/pull/794 解决;

2023-10-23 04:10 UTC, yanghaitao5000 commented
> Updated operator installation method
> 
> ## What type of PR is this?
> * [ ]  Enhancement
> * [ ]  Displaying
> * [ ]  Typo
> * [ ]  Doc Request
> 
> ## Which issue(s) this PR fixes:
> #717 #747
> 
> issue #
> 
> ## What this PR does / why we need it:
> Updated operator deployment method



> Updated operator installation method
> 
> ## What type of PR is this?
> * [ ]  Enhancement
> * [ ]  Displaying
> * [ ]  Typo
> * [ ]  Doc Request
> 
> ## Which issue(s) this PR fixes:
> #717 #747
> 
> issue #
> 
> ## What this PR does / why we need it:
> Updated operator deployment method

2023-10-23 04:11 UTC, closed without merging