v1.0.0->v1.0.1
matrixorigin/matrixorigin.io.cn pull request #886
Opened 2023-12-16 14:56 UTC by yangj1211

## What type of PR is this?

- [ ] Enhancement
- [ ] Displaying
- [ ] Typo
- [x] Doc Request

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

2023-12-16 14:57 UTC, yangj1211 commented
@dengn need to review

2023-12-17 08:38 UTC, dengn requested changes

2023-12-17 08:38 UTC, dengn commented on docs/MatrixOne/Get-Started/install-on-linux/install-on-linux-method1.md
> +MO_DEFAULT_VERSION="v1.0.0"
这里也应该是1.0.1

2023-12-17 08:38 UTC, dengn commented on docs/MatrixOne/Get-Started/install-on-macos/install-on-macos-method1.md
> +MO_DEFAULT_VERSION="v1.0.0"
这里也应该是1.0.1

2023-12-17 08:38 UTC, dengn commented on package-lock.json
> +{
remove this unrelated file

2023-12-17 10:07 UTC, yangj1211 commented
@dengn need to review

2023-12-18 00:52 UTC, dengn approved these changes

2023-12-18 00:52 UTC, merged