update partition
matrixorigin/matrixorigin.io.cn pull request #897
Opened 2023-12-26 04:22 UTC by cyann7

## What type of PR is this?

- [x] Enhancement
- [ ] Displaying
- [ ] Typo
- [ ] Doc Request

## Which issue(s) this PR fixes:

issue #892

## What this PR does / why we need it:

删除了已经完全更新的两个文件（实质是去除tag）：
docs/MatrixOne/Overview/1.1-matrixone-feature-list.md
docs/MatrixOne/Reference/Limitations/1.1-mo-partition-support.md

2023-12-26 04:23 UTC, cyann7 commented
@dengn  need review

2023-12-27 00:57 UTC, dengn requested changes

2023-12-27 00:57 UTC, dengn commented on docs/MatrixOne/Reference/Limitations/mo-partition-support.md
把这个部分从limitation里挪走，挪到reference/SQL语句/DDL/其他/里面，专门建一个partition章节

2023-12-27 02:21 UTC, cyann7 commented on docs/MatrixOne/Reference/Limitations/mo-partition-support.md
已经移过去，但是还都在一个文件，没有拆6个类型的partition，后续进行进一步拆分。

2023-12-27 06:28 UTC, dengn approved these changes

2023-12-27 06:28 UTC, merged