add doc of matrixone-function-list
matrixorigin/matrixorigin.io.cn pull request #912
Opened 2023-12-28 08:15 UTC by yangj1211

## What type of PR is this?

- [ ] Enhancement
- [ ] Displaying
- [ ] Typo
- [x] Doc Request

## Which issue(s) this PR fixes:

issue #908

## What this PR does / why we need it:

2023-12-28 08:16 UTC, yangj1211 commented
@dengn need to review

2023-12-29 02:42 UTC, dengn requested changes

2023-12-29 02:42 UTC, dengn commented on docs/MatrixOne/Overview/matrixone-function-list.md
把这个放到函数列表里面，然后在上面加一个 “函数总表”页面。

<img width="342" alt="image" src="https://github.com/matrixorigin/matrixorigin.io.cn/assets/4965857/225dfaaf-17a2-4fe5-add0-c56d86e84ff1">

2023-12-29 03:05 UTC, yangj1211 commented
@dengn need to review
已更改至Reference/Functions-and-Operators目录下

2023-12-29 05:06 UTC, dengn approved these changes

2023-12-29 05:06 UTC, merged

2023-12-29 05:07 UTC, dengn commented
Main里面也要更新一个函数列表