update main branch
matrixorigin/matrixorigin.io.cn pull request #913
Opened 2023-12-28 09:18 UTC by yangj1211

## What type of PR is this?

- [ ] Enhancement
- [ ] Displaying
- [ ] Typo
- [x] Doc Request

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

2023-12-28 09:22 UTC, yangj1211 commented
@dengn need to review
主要在main分支更新已在1.0.2分支review过的需求
1、增加ucase/upper函数
2、增加MatrixOne的WAL技术设计
3、修改保存查询结果支持文档
4、更新mo最新版本

2023-12-29 02:47 UTC, dengn requested changes

2023-12-29 02:47 UTC, dengn commented on docs/MatrixOne/Deploy/deploy-MatrixOne-cluster.md
> +        参数 VERSION 为要部署的 MatrixOne Operator 的版本号，如 1.0.2。
这个是MatrixOne Operator的版本号，跟matrixone本身的版本号不一致，不需要改。

2023-12-29 02:47 UTC, dengn commented on docs/MatrixOne/Get-Started/install-on-linux/install-on-linux-method2.md
> +Server version: 8.0.30-MatrixOne-v2 MatrixOne
v2？是不是写错了

2023-12-29 03:13 UTC, yangj1211 commented
@dengn need to review
已更正

2023-12-29 05:04 UTC, dengn approved these changes

2023-12-29 05:04 UTC, merged