update FAQs
matrixorigin/matrixorigin.io.cn pull request #927
Opened 2024-01-03 11:00 UTC by yangj1211

## What type of PR is this?

- [ ] Enhancement
- [ ] Displaying
- [ ] Typo
- [x] Doc Request

## Which issue(s) this PR fixes:

issue #903

## What this PR does / why we need it:

2024-01-03 11:01 UTC, yangj1211 commented
@dengn need to review

2024-01-04 01:19 UTC, dengn requested changes

2024-01-04 01:19 UTC, dengn commented on docs/MatrixOne/FAQs/product-faqs.md
> +* **k8s 集群节点当前 dn（也叫 tn）节点是否支持扩容？**
这个就叫TN节点，不用叫DN了。

2024-01-04 01:19 UTC, dengn commented on docs/MatrixOne/FAQs/product-faqs.md
> +* **MatrixOne 是否支持在国产环境下部署？**
这里有大量部署相关的问题，都应该放到部署的faq里去。

2024-01-04 01:19 UTC, dengn commented on docs/MatrixOne/FAQs/product-faqs.md
> +* **MatrixOne 支不支持 Geometry？**
这种是SQL开发层面上的问题，放到sql faq里。

2024-01-04 01:22 UTC, dengn commented
1. 整个FAQ的定位如下：

-Product FAQ里主要是一些general的问题，比如MO是什么，MO有哪些特点，MO能解决什么问题，MO的基础技术架构是什么，MO的适用场景，MO与其他数据库有什么不同这样的问题。
-Deployment FAQ是专门说部署相关的问题的。
-SQL FAQ是专门for用数据库做应用开发碰到相关问题的。

2. 现在FAQ越来越多之后，需要考虑在大的章节里进一步拆分小章节，来对不同的内容进行分类。这样会读起来更顺畅一点。

2024-01-04 06:23 UTC, yangj1211 commented
@dengn need to review
章节是否拆分合理

2024-01-04 13:30 UTC, dengn requested changes

2024-01-04 13:30 UTC, dengn commented on docs/MatrixOne/FAQs/product-faqs.md
> +MatrixOne 当前低版本无法直接升级至最新版本，建议备份数据，进行重装后导入。
这个说的不对，mo从0.8开始都支持从低版本升级到高版本。

2024-01-04 13:30 UTC, dengn commented on docs/MatrixOne/FAQs/product-faqs.md
> +**k8s 集群节点当前 tn 节点是否支持扩容？**
这下面几个问题都是架构相关的

2024-01-04 13:30 UTC, dengn commented on docs/MatrixOne/FAQs/sql-faqs.md
> +## 支持相关
叫 “基本功能相关” 吧

2024-01-05 02:45 UTC, yangj1211 commented
@dengn need to review

2024-01-05 06:05 UTC, dengn approved these changes

2024-01-05 06:06 UTC, merged