update mo-dump link
matrixorigin/matrixorigin.io.cn pull request #930
Opened 2024-01-05 09:56 UTC by yangj1211

## What type of PR is this?

- [ ] Enhancement
- [ ] Displaying
- [ ] Typo
- [x] Doc Request

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

2024-01-07 01:04 UTC, dengn requested changes

2024-01-07 01:04 UTC, dengn commented on docs/MatrixOne/Maintain/backup-restore/modump-backup-restore.md
原文档里 “mo-dump 命令程序嵌入在 MatrixOne 源代码中，你首先需要从 MatrixOne 源代码构建二进制文件。”

这句话没有改掉。实际情况已经不是这样了。

2024-01-07 01:05 UTC, dengn commented
另外mo_dump现在正在增加cicd的自动化发布流程，后面会有独立的release包存在，不再需要做源码编译。
https://github.com/matrixorigin/mo_dump/pull/8

2024-01-09 09:03 UTC, yangj1211 commented
@dengn need to review 

研发测试的时候发布了一个版本release包，但还未正式发布，后续发布再更新文档

2024-01-10 01:17 UTC, dengn approved these changes

2024-01-10 01:17 UTC, merged