update keywords
matrixorigin/matrixorigin.io.cn pull request #976
Opened 2024-02-29 07:03 UTC by yangj1211

## What type of PR is this?

- [ ] Enhancement
- [ ] Displaying
- [ ] Typo
- [x] Doc Request

## Which issue(s) this PR fixes:

issue #

## What this PR does / why we need it:

2024-02-29 08:49 UTC, dengn requested changes
另外增加一个描述，哪些保留关键字是mysql里没有的。专门明确一下。

2024-02-29 08:49 UTC, dengn commented on docs/MatrixOne/Reference/Language-Structure/keywords.md
> +- COMMENT
非保留关键字

2024-02-29 09:49 UTC, yangj1211 commented
@dengn need to review

2024-03-01 04:07 UTC, dengn approved these changes

2024-03-01 04:13 UTC, merged