update explain
matrixorigin/matrixorigin.io.cn pull request #983
Opened 2024-03-12 08:23 UTC by yangj1211

## What type of PR is this?

- [ ] Enhancement
- [ ] Displaying
- [ ] Typo
- [x] Doc Request

## Which issue(s) this PR fixes:

issue #792

## What this PR does / why we need it:

2024-03-12 12:12 UTC, dengn requested changes

2024-03-12 12:12 UTC, dengn commented on docs/MatrixOne/Reference/SQL-Reference/Other/Explain/explain.md
>  MatrixOne 支持任何 `SELECT`，`UPDATE`，`DELETE` 语句执行计划。在 MatrixOne 0.5.1 版本中仅支持 `INSERT` 语句类型中的 `INSERT INTO..SELECT` 语句，暂不支持 `INSERT INTO...VALUES` 语句。
这个版本号描述的明显过老，需要修正。

2024-03-13 03:34 UTC, yangj1211 commented
@dengn need to review

2024-03-14 00:51 UTC, dengn requested changes

2024-03-14 00:51 UTC, dengn commented on docs/MatrixOne/Reference/SQL-Reference/Other/Explain/explain.md
> +MatrixOne 支持任何 `SELECT`，`UPDATE`，`DELETE` 语句执行计划。
现在应该不止了，insert也支持了。

2024-03-19 01:11 UTC, dengn approved these changes

2024-03-19 01:26 UTC, merged