uopdate sql_mode
matrixorigin/matrixorigin.io.cn pull request #986
Opened 2024-03-14 07:33 UTC by yangj1211

## What type of PR is this?

- [ ] Enhancement
- [ ] Displaying
- [ ] Typo
- [x] Doc Request

## Which issue(s) this PR fixes:

issue #985

## What this PR does / why we need it:

2024-03-14 07:35 UTC, yangj1211 commented
存在bug:https://github.com/matrixorigin/matrixone/issues/14968
导致目前无法在配置文件中设置sql_mode
@dengn need to review

2024-03-19 01:14 UTC, dengn requested changes

2024-03-19 01:14 UTC, dengn commented on docs/MatrixOne/Reference/Variable/system-variables/sql-mode.md
> +mysql> SET global sql_mode='ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,STRICT_TRANS_TAB
global和session的使用这里的例子不太对的。按这里设置成global的话，当前session是不会生效的。要重连建立新session才能生效的。

2024-03-19 08:34 UTC, yangj1211 commented
@dengn need to review

2024-03-20 02:31 UTC, dengn requested changes
global的也要单独写个例子。特别需要注意的是，global设置完了之后当前的session并不会生效，要重连才能生效。

2024-04-02 09:13 UTC, dengn approved these changes

2024-04-02 09:13 UTC, merged