case Sensitity
matrixorigin/matrixorigin.io.cn pull request #990
Opened 2024-03-19 04:39 UTC by yangj1211

## What type of PR is this?

- [ ] Enhancement
- [ ] Displaying
- [ ] Typo
- [x] Doc Request

## Which issue(s) this PR fixes:

issue #989

## What this PR does / why we need it:

2024-03-19 04:41 UTC, yangj1211 commented
@dengn need to review

2024-03-19 06:30 UTC, dengn requested changes

2024-03-19 06:30 UTC, dengn commented on docs/MatrixOne/Reference/Variable/system-variables/lower_case_tables_name.md
>  关于 MatrixOne 大小写模式有 5 种，大小写参数 `lower_case_table_names` 可以设置为 0，1，2，3 和 4。
后面3，4，5都去掉了，这里就不用有5种了。

2024-03-20 02:37 UTC, dengn approved these changes

2024-03-20 02:37 UTC, merged